name: ${project.name}
version: ${project.version}
api-version: 1.16
author: "Plug_And_Cree"
depends: [PlaceholderAPI, Vault]

main: it.plugandcree.placeholderchat.PlaceholderChat

commands:
    placeholderchat:
        description: main cmd
